name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        include:
          - image_type: base
            dockerfile: Dockerfile
            image_suffix: ""
            create_release: true
          - image_type: test
            dockerfile: Dockerfile.test
            image_suffix: "-test"
            create_release: false
    uses: actionsforge/actions/.github/workflows/docker-image-release.yml@main
    with:
      dockerfile: ${{ matrix.dockerfile }}
      image-suffix: ${{ matrix.image_suffix }}
      create-release: ${{ matrix.create_release }}
    secrets: inherit
